// Generated by CoffeeScript 1.8.0
(function(window) {
  'use strict';
  var Hangman;
  Hangman = {
    i18n: {
      win: 'Parabéns, você venceu',
      lose: 'Você perdeu :('
    },
    setup: function(elm) {
      var that;
      this.startOver();
      this.gameAnswer = this.chooseWord();
      this.gameShownAnswer = this.blanksFromAnswer(this.gameAnswer);
      this.hangmanState = 0;
      this.drawWord(this.gameShownAnswer);
      this.drawSequence = [this.drawHead, this.drawTorso, this.drawLeftArm, this.drawRightArm, this.drawLeftLeg, this.drawRightLeg];
      if (!elm) {
        return;
      }
      that = this;
      $(elm).on('keyup', function() {
        that.keypress($(elm));
      });
    },
    startOver: function() {
      $('.body-part').remove();
      $('.guessed-letter').remove();
      $('.shown-letter').remove();
    },
    win: function() {
      alert(this.i18n.win);
      this.setup();
    },
    lose: function() {
      alert(this.i18n.lose);
      this.setup();
    },
    inputWords: function() {
      return false;
    },
    words: function() {
      return ['gato', 'cachorro', 'sapo', 'elefante', 'girafa', 'pinguim'] || this.inputWords;
    },
    chooseWord: function() {
      var w;
      w = this.words();
      return w[Math.floor(Math.random() * w.length)];
    },
    blanksFromAnswer: function(answerWord) {
      var i, result;
      result = '';
      for (i in answerWord) {
        result = '_' + result;
      }
      return result;
    },
    alterAt: function(index, letter, originalString) {
      return originalString.substr(0, index) + letter + originalString.substr(index + 1, originalString.length);
    },
    guessLetter: function(letter, shown, answer) {
      var checkIndex;
      if (!letter) {
        return;
      }
      checkIndex = 0;
      checkIndex = answer.indexOf(letter);
      while (checkIndex >= 0) {
        shown = this.alterAt(checkIndex, letter, shown);
        checkIndex = answer.indexOf(letter, checkIndex + 1);
      }
      return shown;
    },
    wrongLetter: function(letter) {
      $('#wrong-letters').append($('<span/>').addClass('guessed-letter').text(letter));
    },
    updateWord: function(answer) {
      var $k, i;
      $k = $('.shown-letter').first();
      for (i in answer) {
        if (answer.charAt(i) !== '_') {
          $k.text(answer.charAt(i));
        } else {
          $k.html('&nbsp;');
        }
        $k = $k.next();
      }
    },
    keypress: function(elm) {
      var tempChar, tempString;
      if (!elm || !elm.val()) {
        return;
      }
      tempChar = $(elm).val().toLowerCase();
      tempString = '';
      $(elm).val('');
      tempString = this.guessLetter(tempChar, this.gameShownAnswer, this.gameAnswer);
      if (tempString !== this.gameShownAnswer) {
        this.updateWord(tempString);
        this.gameShownAnswer = tempString;
        if (this.gameShownAnswer === this.gameAnswer) {
          this.win();
        }
      } else {
        this.wrongLetter(tempChar);
        this.drawSequence[this.hangmanState++]();
        if (this.hangmanState === this.drawSequence.length) {
          this.lose();
        }
      }
    },
    drawWord: function(answer) {
      var i;
      for (i in answer) {
        $('.word-display').append($('<span/>').addClass('shown-letter').html('&nbsp;'));
      }
    },
    drawHead: function() {
      $('.draw-area').append($('<div/>').addClass('body-part head'));
    },
    drawTorso: function() {
      $('.draw-area').append($('<div/>').addClass('body-part armbox').append($('<div/>').addClass('body-part torso')));
      $('.draw-area').append($('<div/>').addClass('body-part legbox').append($('<div/>').addClass('body-part pelvis')));
    },
    drawLeftArm: function() {
      $('.armbox').prepend($('<div/>').addClass('body-part leftarm'));
    },
    drawRightArm: function() {
      $('.armbox').prepend($('<div/>').addClass('body-part rightarm'));
    },
    drawLeftLeg: function() {
      $('.legbox').prepend($('<div/>').addClass('body-part leftleg'));
    },
    drawRightLeg: function() {
      $('.legbox').prepend($('<div/>').addClass('body-part rightleg'));
    }
  };
  window.Hangman = Hangman;
})(this);

$(function() {
  'use strict';
  if (window.Hangman) {
    Hangman.setup('#letter-input');
  }
});
